name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Ejecutar cada 10 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente si quieres

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app
        run: |
          curl -s https://appgdsnavigator-7ueln6kxjeaff8yzmcsqpe.streamlit.app/ > /dev/null
